name: Prevent Direct Push to Master

on:
  push:
    branches:
      - master  # Triggered on direct push to master

jobs:
  block-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check if push is direct
        run: |
          echo "Direct pushes to master are not allowed. Please create a pull request instead."
          exit 1
